// Copyright 2020 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
//
// This file is autogenerated by
//     chrome/android/features/create_stripped_java_factory.py
// Please do not change its content.

package org.chromium.chrome.browser.profile_card;

import android.view.View;

public class ProfileCardCoordinatorFactory {
    public static ProfileCardCoordinator createProfileCardCoordinator(
            View anchorView, CreatorMetadata creatorMetadata) {
        return null;
    }
}
