// Copyright 2018 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package org.chromium.chrome.browser.tab;

import java.nio.ByteBuffer;

/**
 * Interface for associating extra functionality with tabs and allowing
 * extension state to be persisted/restored with normal tab state.
 */
public interface TabExtension {
    /**
     * Restores extension state stored in buffer that was generated by
     * saveToByteBuffer().
     */
    public void restoreFromByteBuffer(ByteBuffer buffer);

    /**
     * Creates a ByteBuffer containing extension state that we want to
     * persisted with other tab state.
     */
    public ByteBuffer saveToByteBuffer();

    /**
     * Notifies this object that the Tab is being destroyed.
     *
     * All references to the Tab and related objects should be cleared inside
     * this method.
     */
    public void onTabDestroy();
}
