// Copyright 2019 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'chrome://resources/cr_elements/cr_button/cr_button.m.js';
import 'chrome://resources/cr_elements/cr_dialog/cr_dialog.m.js';
import './theme_icon.js';

import {assert} from 'chrome://resources/js/assert.m.js';
import {html, PolymerElement} from 'chrome://resources/polymer/v3_0/polymer/polymer_bundled.min.js';

import {BrowserProxy} from './browser_proxy.js';

/**
 * @typedef {{
 *   id:number,
 *   label:string,
 *   frameColor:string,
 *   activeTabColor:string,
 * }}
 */
let ChromeTheme;

/**
 * @param {skia.mojom.SkColor} skColor
 * @return {string}
 */
function skColorToRgb(skColor) {
  const r = (skColor.value >> 16) & 0xff;
  const g = (skColor.value >> 8) & 0xff;
  const b = skColor.value & 0xff;
  return `rgb(${r}, ${g}, ${b})`;
}

/**
 * @param {string} hexColor
 * @return {skia.mojom.SkColor}
 */
function hexColorToSkColor(hexColor) {
  if (!/^#[0-9a-f]{6}$/.test(hexColor)) {
    return {value: 0};
  }
  const r = parseInt(hexColor.substring(1, 3), 16);
  const g = parseInt(hexColor.substring(3, 5), 16);
  const b = parseInt(hexColor.substring(5, 7), 16);
  return {value: 0xff000000 + (r << 16) + (g << 8) + b};
}

/**
 * Dialog that lets the user customize the NTP such as the background color or
 * image.
 * TODO(crbug.com/1032327): Add keyboard support.
 * TODO(crbug.com/1032328): Add support for selecting background image.
 * TODO(crbug.com/1032333): Add support for selecting shortcuts vs most visited.
 */
class CustomizeDialogElement extends PolymerElement {
  static get is() {
    return 'ntp-customize-dialog';
  }

  static get template() {
    return html`{__html_template__}`;
  }

  static get properties() {
    return {
      /** @private {!Array<!ChromeTheme>} */
      chromeThemes_: Array,
      /** @private {!newTabPage.mojom.Theme} */
      theme_: Object,
    };
  }

  constructor() {
    super();
    const {callbackRouter, handler} = BrowserProxy.getInstance();
    /** @private {!newTabPage.mojom.PageCallbackRouter} */
    this.callbackRouter_ = callbackRouter;
    /** @private {newTabPage.mojom.PageHandlerRemote} */
    this.pageHandler_ = handler;
    /** @private {?number} */
    this.setThemeListenerId_ = null;
  }

  /** @override */
  connectedCallback() {
    super.connectedCallback();
    this.pageHandler_.getCustomizeInfo().then(
        ({info: {currentTheme, chromeThemes}}) => {
          this.chromeThemes_ = chromeThemes.map(
              theme => ({
                id: theme.id,
                label: theme.label,
                frameColor: skColorToRgb(theme.colors.frame),
                activeTabColor: skColorToRgb(theme.colors.activeTab),
              }));
          this.theme_ = currentTheme;
          this.$.dialog.showModal();
        });
    this.setThemeListenerId_ =
        this.callbackRouter_.setTheme.addListener(theme => {
          this.theme_ = theme;
          if (theme.type != newTabPage.mojom.ThemeType.AUTOGENERATED) {
            return;
          }
          const rgbFrameColor =
              skColorToRgb(theme.info.autogeneratedThemeColors.frame);
          const rgbActiveTabColor =
              skColorToRgb(theme.info.autogeneratedThemeColors.activeTab);
          this.$.autogeneratedTheme.style.setProperty(
              '--ntp-theme-icon-frame-color', rgbFrameColor);
          this.$.autogeneratedTheme.style.setProperty(
              '--ntp-theme-icon-stroke-color', rgbFrameColor);
          this.$.autogeneratedTheme.style.setProperty(
              '--ntp-theme-icon-active-tab-color', rgbActiveTabColor);
        });
  }

  /** @override */
  disconnectedCallback() {
    super.disconnectedCallback();
    this.callbackRouter_.removeListener(assert(this.setThemeListenerId_));
  }

  /** @private */
  onCancelClick_() {
    this.pageHandler_.revertThemeChanges();
    this.$.dialog.cancel();
  }

  /** @private */
  onDoneClick_() {
    this.pageHandler_.confirmThemeChanges();
    this.$.dialog.close();
  }

  /**
   * @param {!Event} e
   * @private
   */
  onCustomFrameColorChange_(e) {
    this.pageHandler_.applyAutogeneratedTheme(
        hexColorToSkColor(e.target.value));
  }

  /** @private */
  onAutogeneratedThemeClick_() {
    this.$.colorPicker.click();
  }

  /** @private */
  onDefaultThemeClick_() {
    this.pageHandler_.applyDefaultTheme();
  }

  /**
   * @param {!Event} e
   * @private
   */
  onChromeThemeClick_(e) {
    this.pageHandler_.applyChromeTheme(
        this.$.themes.itemForElement(e.target).id);
  }

  /**
   * @param {string|number} id
   * @return {boolean}
   * @private
   */
  isThemeIconSelected_(id) {
    if (!this.theme_) {
      return false;
    }
    if (id == 'autogenerated') {
      return this.theme_.type == newTabPage.mojom.ThemeType.AUTOGENERATED;
    } else if (id == 'default') {
      return this.theme_.type == newTabPage.mojom.ThemeType.DEFAULT;
    } else {
      return this.theme_.type == newTabPage.mojom.ThemeType.CHROME &&
          id == this.theme_.info.chromeThemeId;
    }
  }
}

customElements.define(CustomizeDialogElement.is, CustomizeDialogElement);
