#!/usr/bin/env python
# Copyright 2020 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
"""Creates .ssargs file for SuperSize."""

import argparse
import os
import sys


def main():
  parser = argparse.ArgumentParser()
  parser.add_argument('output', type=argparse.FileType('w'),
                      help='Output filename.')
  parser.add_argument('--items',
                      nargs='*',
                      default=[],
                      help='Line specifying a single Container.')
  args = parser.parse_args()
  lines = ['# Generated by {}'.format(os.path.basename(__file__))] + args.items
  args.output.write('\n'.join(lines + ['']))


if __name__ == '__main__':
  main()
